//!! generated by tsickle from marketing/glue/lib/copy/index.ts
import { Component } from '../base';
declare interface CopyDef {
    reset: () => void;
}
/**
 * A class to copy text input content to clipboard.
 */
declare class Copy extends Component implements CopyDef {
    private successMsg;
    private failMsg;
    private readonly copyButtonEl;
    private readonly copyValueEl;
    private readonly selection;
    private readonly popoverParentEl;
    private originalLabel;
    private readonly clickHandler;
    private readonly keyDownHandler;
    private readonly closeHandler;
    /** @param root root element for the Copy component. */
    constructor(root: HTMLElement);
    /** Initializes the copy component. */
    private init;
    /**
     * Resets component and removes all event listeners.
     */
    destroy(): void;
    /** Copies text input string to clipboard. */
    private copy;
    /**
     * Resets input and copy button and re-enables copy button.
     */
    reset(): void;
}
export { Copy };
