//!! generated by tsickle from marketing/glue/lib/expansionpanels/index.ts
import { Component } from '../base';
import { ExpansionPanelOptions } from './model';
/**
 * Class for creating expansion panels panel group.
 */
declare class ExpansionPanels extends Component {
    private readonly options;
    private readonly model;
    private readonly statusChangeHandler;
    private readonly modelKey;
    private readonly toggleAllComponents;
    private readonly panelContentComponents;
    private readonly panelToggleComponents;
    /**
     * @param root The HTML element containing the panel group.
     * @param options Expansion Panels options object.
     */
    constructor(root: HTMLElement, options?: Partial<ExpansionPanelOptions>);
    /**
     * Initialize the component.
     */
    private init;
    destroy(): void;
    /**
     * Update the class on panel group root indicating current status
     */
    private updateStatus;
}
export { ExpansionPanels };
