//!! generated by tsickle from marketing/glue/lib/header/steppednav/pages.ts
import { Component } from '../../base/';
import { Observer } from '../../observer';
import { DataModel } from './constants';
/**
 * Glue Page component
 */
declare class Pages extends Component {
    private readonly observer;
    private readonly pageEls;
    private model;
    private readonly elementIds;
    selectableElements: Element[];
    private readonly handleUpdate;
    /**
     * @param root Root element that contains options object
     * @param model A shared model for paginating.
     */
    constructor(root: HTMLElement, observer: Observer<DataModel>);
    /**
     * Initialize the component.
     */
    initialize(): void;
    /**
     * Set IDs for all elements.
     */
    private initPageElementIDs;
    /**
     * Updates CSS classes, ARIA properties and event handlers on page elements.
     */
    private update;
    /**
     * Updates the DOM attributes.
     */
    private updatePageElements;
    /**
     * Gets current page parent page index.
     */
    getCurrentPageParentIndex(): number;
    destroy(): void;
}
export { Pages };
