//!! generated by tsickle from marketing/glue/lib/footer/index.ts
import { Component } from '../base';
declare interface FooterOptions {
    panelsBreakpoints: string[];
    isAnimated: boolean;
    columnCount: number;
}
declare interface FooterDef {
    configureExpansionPanels: (isPanels: boolean) => void;
}
/**
 * Class for creating Footer.
 */
declare class Footer extends Component implements FooterDef {
    options: FooterOptions;
    private readonly responsiveSitelinks?;
    private panelsComponent?;
    private readonly panelsOptions;
    private readonly panelGroupEl;
    /**
     * @param root The element that contains the footer sitelinks.
     * @param options Footer sitelink options.
     */
    constructor(root: HTMLElement, options?: Partial<FooterOptions>);
    /**
     * Default footer sitelinks options.
     */
    static get defaults(): FooterOptions;
    /**
     * Destroy the component.
     */
    destroy(): void;
    /**
     * Configure expansion panels if they exist
     */
    configureExpansionPanels(isPanels: boolean): void;
}
export { Footer, type FooterOptions };
