//!! generated by tsickle from marketing/glue/lib/constants/classes.ts
/**
 * @fileoverview A list of Glue classes.
 */
declare enum CssClasses {
    SHOW = "glue-is-shown",
    ACTIVE = "glue-is-active"
}
export { CssClasses };
