//!! generated by tsickle from marketing/glue/lib/focus/index.ts
/**
 * @fileoverview Utilities relating to keyboard focus.
 */
/**
 * Query selectors for elements that can receive focus.
 * Include Material 3 custom elements that Glue uses.
 */
declare const FOCUSABLE_ELEMENT_SELECTORS: string[];
/**
 * Returns true if the element is able to receive focus. Note that this will
 * return true even for elements where the user isn't able to move focus
 * to the element but javascript is able to move focus.
 * @param el The Element to check for focusability.
 * @return Returns true if the element is focusable
 */
declare function isElementFocusable(el: Element): boolean;
/**
 * Get all child focusable elements.
 * @param el The parent element.
 * @return Array containing all child focusable elements.
 */
declare function getFocusableElements(el: Element): HTMLElement[];
export { FOCUSABLE_ELEMENT_SELECTORS, getFocusableElements, isElementFocusable };
