//!! generated by tsickle from marketing/glue/lib/header/deepnav/constants.ts
declare enum Strings {
    ERROR_MSG_NO_CHILDREN = "has no element children.",
    ERROR_PREFIX = "Menubar constructor argument el "
}
export { Strings };
