//!! generated by tsickle from marketing/glue/lib/header/deepnav/index.ts
import { Component } from '../../base';
import { Menu, MenuController } from '../popupmenu/constants';
/**
 * This class creates a navigation menu bar instance, each menu item may control
 * a dropdown sub menu.
 */
declare class Menubar extends Component implements Menu {
    /** A collection of the menu items */
    readonly menubarItems: MenuController[];
    /** A collection of the first characters of each menu item label */
    private readonly firstChars;
    /** The first  menu item. */
    private firstItem;
    /** The last  menu item. */
    private lastItem;
    /** A flag to show menubar's focus status. */
    hasFocus: boolean;
    /** A flag to show menubar's hover status. */
    hasHover: boolean;
    constructor(root: HTMLElement);
    /**
     * Initializes the menubar component.
     * Throws an error if the menubar is empty.
     */
    init(): void;
    destroy(): void;
    /**
     * Sets focus to the specified menu item.
     */
    private setFocusToItem;
    setFocusToFirstItem(): void;
    setFocusToLastItem(): void;
    /**
     * Sets focus to the previous menu item.
     * If the current item is the first menu item, move focus to the last
     * menu item.
     */
    setFocusToPreviousItem(currentItem: MenuController): void;
    /**
     * Sets focus to the next menu item.
     * If the current item is the last menu item, move focus to the first
     * menu item.
     */
    setFocusToNextItem(currentItem: MenuController): void;
    /**
     * Sets focus to the menu item based on the first Character.
     * Search matching label from the current item, if it hits the end,
     * start from the first item, vice versa.
     */
    setFocusByFirstCharacter(currentItem: MenuController, char: string): void;
}
export { Menubar };
