//!! generated by tsickle from marketing/glue/lib/base/index.ts
/**
 * @fileoverview Parent class for Vanilla components
 */
declare interface ComponentDef {
    destroy: () => void;
}
declare abstract class Component implements ComponentDef {
    readonly root: HTMLElement;
    constructor(root: HTMLElement);
    /**
     * Subclasses may implement this method to release any resources / deregister
     * any listeners they have attached. An example of this might be
     * deregistering a resize event from the window object.
     */
    destroy(): void;
    /**
     * Fires a cross-browser-compatible custom event from the component root of
     * the given type, with the given data.
     */
    emit(evtType: string, evtData: unknown, shouldBubble?: boolean): void;
}
export { Component, type ComponentDef };
