//!! generated by tsickle from marketing/glue/lib/base/utils.ts
/**
 * @fileoverview Shared utility functions for Glue components.
 */
/**
 * Available placement options.
 */
export type Placement = 'top' | 'bottom' | 'left' | 'right';
/**
 * Calculates left/top coordinates for an Overlay element based on the
 * position of the Trigger element and the placement option (default: bottom).
 *
 * By default is uses auto placement which will try to position the Overlay
 * relative to the middle of the trigger element.
 * If there is not enough space it will try to position the Overlay on the
 * opposite side of the trigger element.
 * If there is not enough space on the opposite side it will try to position
 * the Overlay on the edge of the window.
 *
 * If placement is set to left/right/top/bottom it will try to position the
 * Overlay on the specified side of the trigger element. If there is not enough
 * space it will use the auto positioning logic.
 *
 *
 * @param root Root element that contains the Content and Trigger elements.
 * @param overlay Element that contains Overlay content.
 * @param trigger Element that triggers the Overlay.
 * @param placement? Placement of the Overlay, default is bottom. Possible
 *     values are: left, right, top, bottom.
 * @return Array containing overlay absolute positions [left, top].
 */
export declare function getOverlayAutoPosition(root: HTMLElement, overlay: HTMLElement, trigger: HTMLElement, placement?: Placement): number[] | null;
