//!! generated by tsickle from marketing/glue/lib/math/coordinate.ts
/**
 * @fileoverview A utility class for representing two-dimensional positions.
 */
/**
 * Class for representing coordinates and positions.
 */
declare class Coordinate {
    x: number;
    y: number;
    constructor(leftCoordinate?: number, topCoordinate?: number);
    /**
     * Returns the difference between two coordinates as a new
     * Coordinate.
     */
    static difference(dimOne: Coordinate, dimTwo: Coordinate): Coordinate;
}
export { Coordinate };
