//!! generated by tsickle from marketing/glue/lib/tabpanels/index.ts
import { Component } from '../base/index';
import { Tabs } from '../tabs';
declare interface TabPanelsOptions {
    panelsBreakpoints: string[];
    isPanelsAnimated: boolean;
    isResponsive: boolean;
    panelsCount: number;
}
declare interface TabPanelsDef {
    tabsComponent?: Tabs;
}
declare class TabPanels extends Component implements TabPanelsDef {
    private readonly options;
    private panelsComponent?;
    tabsComponent?: Tabs;
    private readonly panelsoptions?;
    private readonly tablistEl;
    private readonly panelsEl;
    private currentTab;
    private responsiveTabsMonitor;
    constructor(root: HTMLElement, options?: Partial<TabPanelsOptions>);
    /** Init the component. */
    private initialize;
    /**
     * Default responsive tabs options.
     */
    static get defaults(): TabPanelsOptions;
    /**
     * Set up the Tabs Component.
     */
    private configureTabs;
    /**
     * Set up the Expansion Panels Component.
     */
    private configureExpansionPanels;
    /**
     * @see {Component.destroy}
     */
    destroy(): void;
}
export { TabPanels, type TabPanelsOptions };
