//!! generated by tsickle from marketing/glue/lib/social/constants.ts
/**
 * @fileoverview Constants used by the Social component.
 */
declare enum CssClasses {
    SOCIAL_ROOT = "glue-social",
    PERSISTENT_VARIANT = "glue-social--persistent",
    COLOR_VARIANT = "glue-social--color",
    MONOCHROME_VARIANT = "glue-social--monochrome",
    PARTIAL_MONOCHROME_VARIANT = "glue-social--partialmonochrome",
    PANELS_VARIANT = "glue-social--zippy",
    PANELS_OPPOSITE_VARIANT = "glue-social--zippy-opposite",
    SOCIAL_GROUP = "glue-social__group",
    SOCIAL_LIST = "glue-social__list",
    SOCIAL_TITLE = "glue-social__title",
    SOCIAL_TITLE_INLINE = "glue-social__title--inline",
    SOCIAL_TITLE_ZIPPY = "glue-social__title--zippy",
    SOCIAL_ITEM = "glue-social__item",
    COPY_ROOT = "glue-social__copy",
    COPY_BUTTON = "glue-social__copy-btn",
    COPY_INPUT = "glue-social__copy-input",
    PANELS_SHARE_ICON = "glue-social__share-icon",
    LINK_ROOT = "glue-social__link",
    ICON_CLASSES = "glue-icon glue-icon--social glue-icon--24px",
    POPOVER_ROOT = "glue-social__popover",
    POPOVER_CLOSE = "glue-social__close-btn",
    POPOVER_DIALOG = "glue-social__dialog",
    POPOVER_TRIGGER = "glue-social__icon-trigger",
    TOOLTIP_ROOT = "glue-social__tooltip",
    TOOLTIP_TRIGGER = "glue-social__tooltip-trigger",
    TOOLTIP_CONTENT = "glue-social__tooltip-content",
    VISUALLY_HIDDEN = "glue-visually-hidden"
}
export { CssClasses };
