//!! generated by tsickle from marketing/glue/lib/social/index.ts
/**
 * @fileoverview Glue Social component
 * Initializes available subcomponents (popover, copy, expansion panels)
 */
import { Component } from '../base';
import { Tooltip } from '../tooltip';
declare interface SocialDef {
    tooltipComponents: Tooltip[];
}
declare class Social extends Component implements SocialDef {
    private readonly copyEl;
    private copyComponent?;
    private readonly popoverEl;
    private popoverComponent?;
    private readonly panelsEl;
    private readonly panelTitleEl;
    private readonly socialListEl;
    private expanelsComponent?;
    private readonly tooltipEls;
    tooltipComponents: Tooltip[];
    /**
     * @param root The social element container.
     */
    constructor(root: HTMLElement);
    /** Initializes the component. */
    private initialize;
    /**
     * Destroys the social instance and any subcomponents.
     */
    destroy(): void;
    /**
     * Sets up copy component if elements are present
     */
    private addCopy;
    /**
     * Removes copy component if present
     */
    private removeCopy;
    /**
     * Sets up popover component if elements are present
     */
    private addPopover;
    /**
     * Removes popover component if present
     */
    private removePopover;
    /**
     * Sets up expansion panels component if elements are present
     */
    private addPanels;
    /**
     * Removes expansion panels component if present
     */
    private removePanels;
    /**
     * Sets up tooltip components if elements are present
     */
    private addTooltips;
    /**
     * Removes tooltip components if present
     */
    private removeTooltips;
}
export { Social };
