//!! generated by tsickle from marketing/glue/lib/ytvideo/videomanager.ts
/**
 * Manages a collection of YouTube videos. Also manages the YouTibe Video API.
 */
declare class YoutubeVideoManager {
    private static instance?;
    private readonly videoObjects;
    static getManager(): YoutubeVideoManager;
    static destroyManager(): void;
    /**
     * Stores the YouTube player object
     * @param id The id of a player.
     * @param player The player instance.
     */
    registerYtPlayer(id: string, player: YT.Player): void;
    /**
     * Destroy a player.
     * @param id The id of a player.
     */
    unregisterYtPlayer(id: string): void;
    /**
     * Get YouTube player object.
     * @param id The id of a player.
     */
    getYtPlayer(id: string): YT.Player | undefined;
}
export { YoutubeVideoManager };
