//!! generated by tsickle from marketing/glue/lib/ambientvideo/index.ts
import { Component } from '../base';
declare interface AmbientVideoDef {
    playVideo: () => void;
    pauseVideo: () => void;
}
/**
 * Glue Ambient Video component
 */
declare class AmbientVideo extends Component implements AmbientVideoDef {
    /** A Button that when clicked play/pause the video. */
    private readonly button;
    /** A Button Icon */
    private readonly icon;
    /** A Video Element of Ambient Player component. */
    private readonly videoContainer;
    /** A Button tooltip with play label */
    private readonly tooltipPlay;
    /** A Button tooltip with pause label */
    private readonly tooltipPause;
    constructor(root: HTMLElement);
    private initialize;
    /**
     * Set default ID value for tooltips if they are not provided.
     */
    private setTooltipId;
    /**
     * Plays video
     */
    playVideo(): Promise<void>;
    /**
     * Pause video
     */
    pauseVideo(): void;
    /**
     * Checks the state of video and play/pause accordingly.
     * Adds/Removes the class to toggle the text of tooltip and svg icon
     */
    private readonly togglePlayerState;
    /**
     * Resets component and removes event listeners.
     */
    destroy(): void;
}
export { AmbientVideo };
