//!! generated by tsickle from marketing/glue/lib/expansionpanels/toggleall/index.ts
import { Component } from '../../base';
/**
 * Class for creating expansion panel toggle all.
 */
declare class ExpansionPanelsToggleAll extends Component {
    private readonly model;
    private readonly statusChangeHandler;
    private readonly clickHandler;
    private readonly keydownHandler;
    private readonly keyupHandler;
    /**
     * @param root The HTML element containing the panel group's toggle all.
     */
    constructor(root: HTMLElement);
    /**
     * Initialize component.
     */
    private init;
    destroy(): void;
    /**
     * Toggles all the panels in the group to either expand or collapsed based
     * on the panel group's status
     */
    private toggleAll;
    /**
     * Triggers a toggleAll on the ENTER or SPACE keyboard event.
     */
    private handleKeydown;
    /**
     * Prevents Firefox from firing a click event on spacebar keyup event
     * Fixes http://b/194148554
     */
    private handleKeyup;
    /**
     * Add a11y features.
     */
    private addA11yFeatures;
    /**
     * Remove a11y features.
     */
    private removeA11yFeatures;
    /**
     * Update the aria-expanded attribute on toggle button
     */
    private updateToggleAllStatus;
}
export { ExpansionPanelsToggleAll };
