//!! generated by tsickle from marketing/glue/lib/banner/constants.ts
/**
 * @fileoverview Constants used by the Banner component.
 */
declare enum CssClasses {
    BANNER = "glue-banner",
    BANNER_CONTENT = "glue-banner__content",
    BANNER_CLOSE_BUTTON = "glue-banner__close-btn",
    BANNER_HIDDEN = "glue-banner--hidden"
}
declare enum Numbers {
    BANNER_CLOSE_DELAY = 300
}
declare enum Strings {
    DEFAULT_CLOSE_BUTTON_ARIA_LABEL = "Hide the banner",
    DEFAULT_EMPHASIS = "low"
}
export { CssClasses, Numbers, Strings };
