//!! generated by tsickle from marketing/glue/lib/banner/index.ts
import { Component } from '../base';
/**
 * Adds class methods here to prevent deletion in the CDN.
 */
declare interface BannerDef {
    close: () => void;
}
/**
 * A class that displays an important message or helps user perform action
 * through links or button.
 */
declare class Banner extends Component implements BannerDef {
    private readonly closeButton;
    constructor(root: HTMLElement);
    private readonly handleClick;
    /**
     * Hides the banner component when close button is clicked or is a
     * public method that can directly be called.
     */
    close(): void;
    /**
     * Removes event listeners.
     */
    destroy(): void;
}
export { Banner };
