//!! generated by tsickle from marketing/glue/lib/header/siteswitcher/constants.ts
declare enum CssClasses {
    COMPONENT = "glue-header__site-switcher",
    MENU = "glue-header__site-switcher-menu",
    MENU_ITEM = "glue-header__item",
    MENU_LINK = "glue-header__link",
    MENU_ITEM_DESCRIPTION = "glue-header__site-switcher-item-description",
    MORE_PRODUCTS = "glue-header__site-switcher-more-products"
}
declare enum Strings {
    NO_ARIA_CONTROL = "aria-control value is not set on the site switcher element.",
    NO_MENU = "Header Site Switcher could not find a menu element."
}
export { CssClasses, Strings };
