//!! generated by tsickle from marketing/glue/lib/header/siteswitcher/index.ts
import { Component } from '../../base/';
import { PopupMenu } from '../popupmenu';
import { MenuController } from '../popupmenu/constants';
/**
 * This class creates a Site Switcher instance, it is triggered to show
 * a list of micro sites options.
 */
declare class SiteSwitcher extends Component implements MenuController {
    parentMenu: null;
    /** A flag to show the switcher's focus status. */
    hasFocus: boolean;
    /** A flag to show switcher's hover status. */
    hasHover: boolean;
    /** The dropdown menu controlled by the site swticher. */
    popupMenu: PopupMenu;
    /**
     * A flag to indicate whether this element is a menubar item. Both the
     * menubar item and site switcher can be dropdown trigger.
     */
    isMenubarItem: boolean;
    constructor(root: HTMLElement);
    init(): void;
    destroy(): void;
    /**
     * Handles keydown events.
     * When press the Space, Enter or Down keys, open the popup menu and focus to
     * the first item. When press the Up key, open the popup menu and focus to
     * the last item.
     */
    private readonly handleKeydown;
    /**
     * Handles the click event.
     * Toggles the menu when users click the site switcher.
     */
    private readonly handleClick;
    /** Sets the expanded attribute when the menu is open. */
    setExpanded(flag: boolean): void;
    /**
     * Sets hasFocus to true when the switcher is focused.
     */
    private readonly handleFocus;
    /**
     * Sets hasFocus to false when the switcher is blurred.
     */
    private readonly handleBlur;
    /**
     * Opens the menu and set hasHover to true when it is hovered.
     */
    private readonly handleMouseenter;
    /**
     * Waits for 300 mills to close the menu after moving mouse out of the
     * switcher.
     */
    private readonly handleMouseLeave;
}
export { SiteSwitcher };
