//!! generated by tsickle from marketing/glue/lib/modal/constants.ts
declare enum CssClasses {
    ROOT = "glue-modal",
    CLOSE_BTN = "glue-modal__close-btn",
    CLOSING = "glue-modal-closing",
    OPEN = "glue-modal-open",
    NO_SCROLL = "glue-no-scroll",
    DARK = "glue-modal--dark"
}
declare enum Strings {
    OPENED_EVENT = "GlueModal:opened",
    CLOSED_EVENT = "GlueModal:closed",
    CLOSE_MODAL_LABEL = "Close the modal"
}
export { CssClasses, Strings };
