//!! generated by tsickle from marketing/glue/lib/expansionpanels/model/modelfactory.ts
/**
 * tslint:disable class-as-namespace
 */
import { ExpansionPanelOptions, ExpansionPanelsModel } from './index';
/**
 * Expansion Panels model factory.
 */
declare class ModelFactory {
    /**
     * Internal list of all registered expansion panels model instances.
     */
    private static instances;
    /**
     * Returns a new or existing expansion panels model instance based on an
     * identifier.
     * Falls back on a default instance if no id is provided.
     */
    static get(id?: string, options?: Partial<ExpansionPanelOptions>): ExpansionPanelsModel;
    /**
     * Clears a single expansion panels model instance.
     */
    static clearSingle(id: string): void;
    /**
     * Clears all existing expansion panels model instances.
     */
    static clearAll(): void;
}
export { ModelFactory };
