//!! generated by tsickle from marketing/glue/lib/header/popupmenu/menuitem.ts
import { Component } from '../../base';
import { MenuController } from './constants';
import { PopupMenu } from './index';
/**
 * This class creates a child menu item component in a menu.
 * This menu item may/not control a popup menu.
 */
declare class MenuItem extends Component implements MenuController {
    readonly parentMenu: PopupMenu;
    isMenubarItem: boolean;
    /** The  popopMenu is the menu controlled by the menu item. */
    popupMenu: PopupMenu | null;
    constructor(root: HTMLLinkElement, parentMenu: PopupMenu);
    init(): void;
    destroy(): void;
    /** Assert this is a MenuItem */
    private controllerWithoutParentMenu;
    /**
     * Handles keydown event on the menu item.
     *
     */
    private readonly handleKeydown;
    setExpanded(flag: boolean): void;
    private readonly handleClick;
    private readonly handleFocus;
    private readonly handleBlur;
    private readonly handleMouseenter;
    private readonly handleMouseleave;
}
export { MenuItem };
