//!! generated by tsickle from marketing/glue/lib/smoothscroll/constants.ts
/**
 * @fileoverview Config typedef and event enum for SmoothScroll.
 */
import { EasingFunctionName, SimpleEasingFunction } from '../easing/';
interface SmoothScrollPosition {
    x: number;
    y: number;
}
interface SmoothScrollOptions {
    duration: number;
    offset: SmoothScrollPosition;
    easing: EasingFunctionName | SimpleEasingFunction;
    hash: boolean;
    direction: string;
    id?: string;
}
declare enum ScrollEventType {
    STARTSCROLL = "glue.smoothScroll.start",
    ENDSCROLL = "glue.smoothScroll.end"
}
declare enum Strings {
    MISSING_PAGE_ELEMENT = "Smooth Scrolling requires a valid page element.",
    DIRECTION_MALFORMED = "Scroll direction value only accepts \"x\", \"y\" or \"both\""
}
declare const defaultOptions: SmoothScrollOptions;
export { defaultOptions, ScrollEventType, Strings, type SmoothScrollOptions, type SmoothScrollPosition, };
