//!! generated by tsickle from marketing/glue/lib/smoothscroll/index.ts
/**
 * @fileoverview The SmoothScroll module allows an animated smooth scroll from
 * one location within the document to another. It broadcasts events when
 * scrolling starts and ends. Configurable parameters include duration of the
 * scroll, offset of the target element, the easing function and URL hash.
 *
 * For documentation and demo see
 * https://glue-docs.appspot.com/docs/components/raw/smoothscroll
 */
import { defaultOptions, SmoothScrollOptions } from './constants';
declare interface SmoothScrollDef {
    scrollToId: (id: string, elementConfig?: Partial<SmoothScrollOptions>) => void;
}
declare class SmoothScroll implements SmoothScrollDef {
    private currentScrollElement;
    private currentScrollElementId;
    private readonly scrollManager;
    private readonly globalConfig;
    constructor(config?: Partial<SmoothScrollOptions>);
    /**
     * Allows an animated smooth scroll from one location within the
     * document to another.
     * @param id Element id.
     * @param elementConfig The config object to use for the scroll.
     */
    scrollToId(id?: string, elementConfig?: Partial<SmoothScrollOptions>): void;
    /**
     * Destroy the component. Removes listeners.
     */
    destroy(): void;
}
export { defaultOptions, SmoothScroll, type SmoothScrollOptions };
