//!! generated by tsickle from marketing/glue/lib/expansionpanels/toggle/index.ts
import { Component } from '../../base';
/**
 * Class for creating expansion panels toggle.
 */
declare class ExpansionPanelsToggle extends Component {
    private readonly model;
    private readonly clickHandler;
    private readonly keydownHandler;
    private readonly contentId;
    /**
     * @param root The HTML element containing the individual panel's toggle.
     */
    constructor(root: HTMLElement);
    /**
     * Initialize the component.
     */
    private init;
    destroy(): void;
    /**
     * Toggles a panel open or closed depending on its current state.
     * Dispatches an event so the panel content targeted will expand/collapse.
     */
    private toggle;
    /**
     * Triggers a toggle on the ENTER or SPACE keyboard event.
     */
    private handleKeydown;
    /**
     * Add a11y features.
     */
    private addA11yFeatures;
    /**
     * Remove a11y features.
     */
    private removeA11yFeatures;
}
export { ExpansionPanelsToggle };
